language: go

go:
  - 1.8.3

script: 
  - go build main.go
  - npm install -g bower
  - cd static ; bower install ; polymer build; cd ..
  - rm main

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash